services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - JELLYFIN_PublishedServerUrl=http://192.168.0.112
    volumes:
      - ./config:/config
      - /home/vvguimaraes/Documentos/Series:/data/tvshows
      - /home/vvguimaraes/Documentos/Filmes:/data/movies
    ports:
      - 8096:8096
    restart: always
